// Utility to load pre-calculated embeddings
// These are generated by scripts/generate_embeddings.js and stored in public/data/embeddings.json

let embeddingsCache: Record<string, number[]> | null = null;
let isLoading = false;

export const loadEmbeddings = async (): Promise<Record<string, number[]> | null> => {
    if (embeddingsCache) return embeddingsCache;
    if (isLoading) {
        // Simple wait loop if already loading (mutex-like)
        while (isLoading) {
            await new Promise(r => setTimeout(r, 100));
            if (embeddingsCache) return embeddingsCache;
        }
    }

    try {
        isLoading = true;
        // In Next.js client-side, fetch relative to public root
        const res = await fetch('/data/embeddings.json');
        if (!res.ok) {
            console.warn("Embeddings file not found. Falling back to string similarity.");
            isLoading = false;
            return null;
        }
        const data = await res.json();
        embeddingsCache = data;
        isLoading = false;
        console.log("Embeddings loaded successfully.");
        return data;
    } catch (e) {
        console.error("Failed to load embeddings:", e);
        isLoading = false;
        return null;
    }
};

export const getEmbedding = (conId: string, sectionId: string): number[] | null => {
    if (!embeddingsCache) return null;
    const key = `${conId}_${sectionId}`;
    return embeddingsCache[key] || null;
};
